config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index", as: 'home'

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, :quantity, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController

	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	def index
		@products = Product.all

	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
	end

	def create
		#code to manage existing products
		@product = Product.new(product_params)	
		if product = Product.find_by(name: @product.name)
			new_qunatity = @product.quantity
			quantity = product.quantity + new_qunatity
			product.update(:quantity => quantity)
			flash[:notice] = "Product was successfully updated"
			return redirect_to product
		else
			#@product = Product.new(product_params)	
			@product.save
			flash[:notice] = "Product was successfully added"
			return redirect_to @product
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if(@product.update(product_params))
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end


	private def product_params
		params.require(:product).permit(:name, :detail, :quantity, :expiry_date)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryManagementProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'  %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Inventory Management</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
         
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Add new Product", new_product_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    <div class="container">
      <% flash.each do |name,msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= form_for :product, url: product_path(@product), method: :patch do |f| %>
	<% if @product.errors.any? %>
		<% @product.errors.full_messages.each do |msg|%>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	
	<p>
		<%= f.label :name %><br>
		<%= f.text_field(:name, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :detail %><br>
		<%= f.text_area(:detail, {:class => 'form-control'})%>
	</p>

	<p>
		<%= f.label :quantity %><br>
		<%= f.text_field(:quantity, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :expiry_date %><br>
		<%= f.text_field :expiry_date, class: 'form-control' %>
		
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/products/index.html.erb
<h1>Product List</h1>
<% @products.each do |product| %>
	<div class="well">
		<h3><%= product.name %></h3>
		<p><%= product.detail %></p>
		<p><%= product.quantity %></p>
		<p><%= product.expiry_date %></p>
		<%= link_to "More Details", product_path(product), :class => 'btn btn-default'%>
	</div>
<% end %>

app/views/products/new.html.erb
<h1>Add new Product</h1>
<%= form_for :product, url: products_path do |f| %>
	<% if @product.errors.any? %>
		<% @product.errors.full_messages.each do |msg|%>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	
	<p>
		<%= f.label :name %><br>
		<%= f.text_field(:name, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :detail %><br>
		<%= f.text_area(:detail, {:class => 'form-control'})%>
	</p>

	<p>
		<%= f.label :quantity %><br>
		<%= f.text_field(:quantity, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :price %><br>
		<%= f.text_field(:price, {:class => 'form-control'}) %>
	</p>

	<p>
		<%= f.label :expiry_date %><br>
		<%= f.text_field :expiry_date, class: 'form-control', :type => "date" %>
		
	</p>
	
	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/products/show.html.erb
<table class="table table-bordered">
	<thead>
	<tr>
		<th>Product Name</th>
		<th>Detail</th>
		<th>Quantity</th>
		<th>Expiry Date</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td><%= @product.name %></td>
		<td><%= @product.detail %></td>
		<td><%= @product.quantity %></td>
		<td><%= @product.expiry_date %></td>
	</tr>
	</tbody>

</table>
<hr>
<%= link_to "Edit", edit_product_path(@product), :class => 'btn btn-default'%>
<%= link_to "Delete", product_path(@product), 
						method: :delete,
						data: {confirm: 'Are you sure?'},
						:class => 'btn btn-danger'%>